include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: false      # Permitimos que dynamic se asigne sin romper la compilación
    strict-inference: false  # Relajamos la inferencia de tipos genéricos
    strict-raw-types: true
  errors:
    avoid_print: warning     # Ya no rompe el pipeline, pasa como advertencia
    invalid_assignment: warning
    argument_type_not_assignable: warning
    missing_required_param: error
    missing_return: error

linter:
  rules:
    - avoid_empty_else
    - prefer_const_constructors
    - prefer_is_empty
    - always_declare_return_types
